version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - 3000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
  php:
    image: php:7.4-fpm
    volumes:
      - ./:/var/www/html